/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authConfirmEmailRouteImport } from './routes/(auth)/confirm-email'
import { Route as AuthenticatedWorkspace_idLayoutRouteImport } from './routes/_authenticated/$workspace_id/_layout'
import { Route as AuthenticatedWorkspace_idLayoutMessagesRouteImport } from './routes/_authenticated/$workspace_id/_layout/messages'
import { Route as AuthenticatedWorkspace_idLayoutDashboardRouteImport } from './routes/_authenticated/$workspace_id/_layout/dashboard'
import { Route as AuthenticatedWorkspace_idLayoutProjectsProject_idRouteImport } from './routes/_authenticated/$workspace_id/_layout/projects/$project_id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authConfirmEmailRoute = authConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedWorkspace_idLayoutRoute =
  AuthenticatedWorkspace_idLayoutRouteImport.update({
    id: '/$workspace_id/_layout',
    path: '/$workspace_id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspace_idLayoutMessagesRoute =
  AuthenticatedWorkspace_idLayoutMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedWorkspace_idLayoutRoute,
  } as any)
const AuthenticatedWorkspace_idLayoutDashboardRoute =
  AuthenticatedWorkspace_idLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedWorkspace_idLayoutRoute,
  } as any)
const AuthenticatedWorkspace_idLayoutProjectsProject_idRoute =
  AuthenticatedWorkspace_idLayoutProjectsProject_idRouteImport.update({
    id: '/projects/$project_id',
    path: '/projects/$project_id',
    getParentRoute: () => AuthenticatedWorkspace_idLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof authConfirmEmailRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/$workspace_id': typeof AuthenticatedWorkspace_idLayoutRouteWithChildren
  '/$workspace_id/dashboard': typeof AuthenticatedWorkspace_idLayoutDashboardRoute
  '/$workspace_id/messages': typeof AuthenticatedWorkspace_idLayoutMessagesRoute
  '/$workspace_id/projects/$project_id': typeof AuthenticatedWorkspace_idLayoutProjectsProject_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof authConfirmEmailRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/$workspace_id': typeof AuthenticatedWorkspace_idLayoutRouteWithChildren
  '/$workspace_id/dashboard': typeof AuthenticatedWorkspace_idLayoutDashboardRoute
  '/$workspace_id/messages': typeof AuthenticatedWorkspace_idLayoutMessagesRoute
  '/$workspace_id/projects/$project_id': typeof AuthenticatedWorkspace_idLayoutProjectsProject_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/confirm-email': typeof authConfirmEmailRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/$workspace_id/_layout': typeof AuthenticatedWorkspace_idLayoutRouteWithChildren
  '/_authenticated/$workspace_id/_layout/dashboard': typeof AuthenticatedWorkspace_idLayoutDashboardRoute
  '/_authenticated/$workspace_id/_layout/messages': typeof AuthenticatedWorkspace_idLayoutMessagesRoute
  '/_authenticated/$workspace_id/_layout/projects/$project_id': typeof AuthenticatedWorkspace_idLayoutProjectsProject_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/onboarding'
    | '/$workspace_id'
    | '/$workspace_id/dashboard'
    | '/$workspace_id/messages'
    | '/$workspace_id/projects/$project_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/onboarding'
    | '/$workspace_id'
    | '/$workspace_id/dashboard'
    | '/$workspace_id/messages'
    | '/$workspace_id/projects/$project_id'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_authenticated'
    | '/(auth)/confirm-email'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/_authenticated/onboarding'
    | '/_authenticated/$workspace_id/_layout'
    | '/_authenticated/$workspace_id/_layout/dashboard'
    | '/_authenticated/$workspace_id/_layout/messages'
    | '/_authenticated/$workspace_id/_layout/projects/$project_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/confirm-email': {
      id: '/(auth)/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof authConfirmEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/$workspace_id/_layout': {
      id: '/_authenticated/$workspace_id/_layout'
      path: '/$workspace_id'
      fullPath: '/$workspace_id'
      preLoaderRoute: typeof AuthenticatedWorkspace_idLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$workspace_id/_layout/messages': {
      id: '/_authenticated/$workspace_id/_layout/messages'
      path: '/messages'
      fullPath: '/$workspace_id/messages'
      preLoaderRoute: typeof AuthenticatedWorkspace_idLayoutMessagesRouteImport
      parentRoute: typeof AuthenticatedWorkspace_idLayoutRoute
    }
    '/_authenticated/$workspace_id/_layout/dashboard': {
      id: '/_authenticated/$workspace_id/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/$workspace_id/dashboard'
      preLoaderRoute: typeof AuthenticatedWorkspace_idLayoutDashboardRouteImport
      parentRoute: typeof AuthenticatedWorkspace_idLayoutRoute
    }
    '/_authenticated/$workspace_id/_layout/projects/$project_id': {
      id: '/_authenticated/$workspace_id/_layout/projects/$project_id'
      path: '/projects/$project_id'
      fullPath: '/$workspace_id/projects/$project_id'
      preLoaderRoute: typeof AuthenticatedWorkspace_idLayoutProjectsProject_idRouteImport
      parentRoute: typeof AuthenticatedWorkspace_idLayoutRoute
    }
  }
}

interface authRouteRouteChildren {
  authConfirmEmailRoute: typeof authConfirmEmailRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authConfirmEmailRoute: authConfirmEmailRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedWorkspace_idLayoutRouteChildren {
  AuthenticatedWorkspace_idLayoutDashboardRoute: typeof AuthenticatedWorkspace_idLayoutDashboardRoute
  AuthenticatedWorkspace_idLayoutMessagesRoute: typeof AuthenticatedWorkspace_idLayoutMessagesRoute
  AuthenticatedWorkspace_idLayoutProjectsProject_idRoute: typeof AuthenticatedWorkspace_idLayoutProjectsProject_idRoute
}

const AuthenticatedWorkspace_idLayoutRouteChildren: AuthenticatedWorkspace_idLayoutRouteChildren =
  {
    AuthenticatedWorkspace_idLayoutDashboardRoute:
      AuthenticatedWorkspace_idLayoutDashboardRoute,
    AuthenticatedWorkspace_idLayoutMessagesRoute:
      AuthenticatedWorkspace_idLayoutMessagesRoute,
    AuthenticatedWorkspace_idLayoutProjectsProject_idRoute:
      AuthenticatedWorkspace_idLayoutProjectsProject_idRoute,
  }

const AuthenticatedWorkspace_idLayoutRouteWithChildren =
  AuthenticatedWorkspace_idLayoutRoute._addFileChildren(
    AuthenticatedWorkspace_idLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedWorkspace_idLayoutRoute: typeof AuthenticatedWorkspace_idLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedWorkspace_idLayoutRoute:
    AuthenticatedWorkspace_idLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
